spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: phong
    password: phong
    name: product-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serializer.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.example.ecommerce.notification.PaymentNotificationRequest

server:
  port: 8060